import Foundation

/// A single message in a chat conversation.
public struct ChatMessage: Identifiable, Sendable {

    /// A stable unique identifier for this message.
    public let id: UUID

    /// The role of the message author.
    public let role: Role

    /// The text content of the message.
    public let content: String

    /// The time the message was created.
    public let timestamp: Date

    /// Identifies who authored a chat message.
    public enum Role: String, Sendable {
        /// A message sent by the user.
        case user
        /// A message generated by the language model.
        case assistant
    }

    /// Creates a new chat message.
    ///
    /// - Parameters:
    ///   - role: The author of the message.
    ///   - content: The text content.
    ///   - id: A unique identifier. Defaults to a new UUID.
    ///   - timestamp: The creation time. Defaults to now.
    public init(
        role: Role,
        content: String,
        id: UUID = UUID(),
        timestamp: Date = Date()
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.timestamp = timestamp
    }
}
